
###Get all users
GET http://localhost:3000/users

### Get a user
GET http://localhost:3000/users/60153bee116d451e2488588d

### Create a user
POST http://localhost:3000/users
Content-Type:application/json

{
"name":"Camille",
"email":"j.c@gmail.com",
"password":"sdfsdf"
}

### Login a user
POST http://localhost:3000/users/login
Content-Type:application/json

{
"email":"bb@bbbb",
"password":"bbbb"
}

### Delete a user
DELETE http://localhost:3000/users/601538202f40bc1704053114

### Update a user
PATCH http://localhost:3000/users/6026a97c5325c10022167663
Content-Type:application/json

{
"name":"Jojan"
}

### Delete all users
DELETE http://localhost:3000/users